export const countryData = [
    { label: 'Select a Country', value: '' },
    { label: 'United States', value: 'USD' },
    { label: 'China', value: 'CNY' },
    { label: 'Japan', value: 'JPY' },
    { label: 'India', value: 'INR' },
    { label: 'Germany', value: 'EUR' },
    { label: 'United Kingdom', value: 'GBP' },
    { label: 'France', value: 'EUR' },
    { label: 'Brazil', value: 'BRL' },
    { label: 'Italy', value: 'EUR' },
    { label: 'Canada', value: 'CAD' },
    { label: 'South Korea', value: 'KRW' },
    { label: 'Australia', value: 'AUD' },
    { label: 'Spain', value: 'EUR' },
    { label: 'Mexico', value: 'MXN' },
    { label: 'Indonesia', value: 'IDR' },
    { label: 'Netherlands', value: 'EUR' },
    { label: 'Turkey', value: 'TRY' },
    { label: 'Saudi Arabia', value: 'SAR' },
    { label: 'Switzerland', value: 'CHF' },
    { label: 'Argentina', value: 'ARS' },
    { label: 'Sweden', value: 'SEK' },
    { label: 'Poland', value: 'PLN' },
    { label: 'Belgium', value: 'EUR' },
    { label: 'Thailand', value: 'THB' },
    { label: 'Austria', value: 'EUR' },
    { label: 'Norway', value: 'NOK' },
    { label: 'United Arab Emirates', value: 'AED' },
    { label: 'Israel', value: 'ILS' },
    { label: 'Malaysia', value: 'MYR' },
    { label: 'Singapore', value: 'SGD' },
    { label: 'South Africa', value: 'ZAR' },
    { label: 'Denmark', value: 'DKK' },
    { label: 'Ireland', value: 'EUR' },
  ];